### PR TITLE
New iOS API Reference

### PR DESCRIPTION
**Pull request by gzerad**

### CODE REVIEW

**Comment by ygit** [comment]
I’m not able to check the Docs Site preview on the API References PR

https://user-images.githubusercontent.com/8512357/235126554-61c73a0f-a0b8-4a37-bbec-eb3828851aa3.mov

**Review by ygit — APPROVED** [review]
LGTM

**Comment by pawan-100ms** [comment]
I ended up checking the deployment on the phone. I couldn’t see API references. But visible on desktop. Is it missing on mobile view?

**Review by pawan-100ms — APPROVED** [review]
Looks really good!

**Pull request merged**
